name: Pylint

on: [push]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Checking if I can get terraform on this project
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest
    - name: Terraform version
      id: version
      run: terraform version
